name: ARKANfotografix
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40641
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#181617'
    - '#222222'
    - '#0c0c0c'
    - '#271414'
  brandStrength: 0.875
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
