typography_spectrum: 0.40641
color:
  brandColors:
    - '#000000'
    - '#181617'
    - '#222222'
    - '#0c0c0c'
    - '#271414'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24559
analytics:
  google: null
  facebook: null
  twitter: null
name: ARKANfotografix
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: null
purpose: []
